name: EmptyWorld
version: 1.0-SNAPSHOT
main: pro.gamerexde.emptyworld.Main
api-version: 1.13
author: [Gamerexde]
description: No Blocks, No Animals, No Monsters, No Lag.
website: https://www.gamerexde.pro/
commands:
  emptyworld:
